var Main_Controller=Controller.extend({construct:function(){this.SC.construct();this._canMoveForward=true;this._stageSpriteArray=new Array();this._lastObstacles=new Array();this._hitTestQuadrants=new Array();this._player;this._rotater;this._startScreen;this._stage;this._activeStickyObject=null;this._lastRotation;this._angle=0;this._stageRotation=0;this._moveDistance=10;this._quadSize=100;this._thoughtBubble;this._mask;this._lastInteractTime;this._touchWalkInterval;this._MIND;this._topZIndex=1000;this._maxLoad=903968
this._startScreenInformation;this._startScreenDisclaimer;this._timer;this._audio;this._gameActive;this._gameOver;this._volumeControl;this._endScreenGood;this._endScreenBad;this._swipeInterface;this._gameActive;this._tileCount;this._currentTile;this._startMatrix;this._potentialThoughtArray=new Array();this._preTriggeredControls=new Array();this._mainModel;},init:function(model){this._gameActive=false;this._gameOver=false;this._mainModel=model;this.addListners();this.addPlayer(this._mainModel.getPlayerInfo());this.addRotater(this._mainModel.getRotaterX(),this._mainModel.getRotaterY(),this._mainModel.getStageWidth(),this._mainModel.getStageHeight());this.addStage(this._mainModel.getStageStartX(),this._mainModel.getStageStartY(),this._mainModel.getStageWidth(),this._mainModel.getStageHeight());this.createHitTestQuadrants();this.addStartMatrix(this._mainModel.getThoughtMatrix());this.addPotentialThoughtArray(this._mainModel.getPotentialThoughtArray());this.populatePretriggeredControls(this._potentialThoughtArray);this.buildStage(this._mainModel.getGameBoard());},init2:function(){this.registerPairs();this.registerHingedDoors();this.addMask();this.addThoughtBubble();this.addOCD_control();this.addEndScreen();this.addTimer();this.addAudio();$(document).keypress(this.catchKeyPress.bind(this));$(document).keydown(this.catchKeyDown.bind(this));$(document).keyup(this.catchKeyUp.bind(this));g_afterAssetsLoad();},addListners:function(){g_eventHandler.addAListener("movementProgress",this);g_eventHandler.addAListener("checkForHit",this);g_eventHandler.addAListener("setCanMoveForward",this);g_eventHandler.addAListener("removeRect",this);g_eventHandler.addAListener("registerRect",this);g_eventHandler.addAListener("stickyObjectLifted",this);g_eventHandler.addAListener("stickyObjectDropped",this);g_eventHandler.addAListener("gameOver",this);g_eventHandler.addAListener("addNextSprite",this);g_eventHandler.addAListener("addAssociatedThought",this);g_eventHandler.addAListener("showGameDisplay",this);g_eventHandler.addAListener("screenRotatedPortrait",this);g_eventHandler.addAListener("screenRotatedLandscape",this);g_eventHandler.addAListener("checkPositionForFinish",this);g_eventHandler.addAListener("restartGame",this);g_eventHandler.addAListener("updateMovableTiles",this);},addPlayer:function(playerInfo){var classAcronym=playerInfo.type;var data={className:this._mainModel.getGameboardClasses()[classAcronym],imgs:this._mainModel.getGameboardImageLookup()[classAcronym],id:'player',container:"body",x:playerInfo.x,y:playerInfo.y,w:playerInfo.w,h:playerInfo.h,stopFrame:playerInfo.stopFrame,walkFrames:playerInfo.walkFrames,turnLeftFrame:playerInfo.turnLeftFrame,turnRightFrame:playerInfo.turnRightFrame,interactFrame:playerInfo.interactFrame,stickyLiftOffset:playerInfo.stickyLiftOffset,stickyLiftOffset:playerInfo.stickyLiftOffset,startFrame:0}
var hitTestHeadData=playerInfo.hitTestHeadData;hitTestHeadData.container=data.id;var hitTestTorsoData=playerInfo.hitTestTorsoData;hitTestTorsoData.container=data.id;this._player=new Player_OCD_Controller();var newView=new Player_View();this._player.bindView(newView,data);var newHittestViewHead=new DispatchingNonGraphic_View();this._player.bindHitTestHeadView(newHittestViewHead,hitTestHeadData);var newHittestViewTorso=new DispatchingNonGraphic_View();this._player.bindHitTestTorsoView(newHittestViewTorso,hitTestTorsoData);this._player.hide();},addStartMatrix:function(matrix){this._startMatrix=matrix;},addPotentialThoughtArray:function(array){this._potentialThoughtArray=array;},populatePretriggeredControls:function(array){this._preTriggeredControls=new Array();var temp=array.slice(0);for(var i=0;i<5;i++){var randomPosition=this.getRandomInt(0,temp.length);var tempIndex=temp.splice(randomPosition,1);this._preTriggeredControls.push(tempIndex);}},turnOnRandomizedItems:function(){for(var i=0;i<this._preTriggeredControls.length;i++){var type=this._startMatrix[this._preTriggeredControls[i]].getObjectType();if(type=="immobile"){this.interactionResponse(this._startMatrix[this._preTriggeredControls[i]]);if(this.getRandomInt(0,5)==1){this.interactionExtendedActions(this._startMatrix[this._preTriggeredControls[i]],this.getRandomInt(1,2));}}else{this.interactionExtendedActions(this._startMatrix[this._preTriggeredControls[i]],this.getRandomInt(1,2));}}},addAssociatedThought:function(data){var relatedThoughts=this._mainModel.getRelatedMatrix()[data.type];if(relatedThoughts.length>0){var position=this.getRandomInt(0,relatedThoughts.length);var thoughtToAdd=relatedThoughts[position];if(this.getRandomInt(0,4)==1){if(thoughtToAdd!=undefined){console.log("add thought at random : "+thoughtToAdd);this.interactionExtendedActions(this._startMatrix[thoughtToAdd],1);}}}},updateMatrixViewPointer:function(type,view){this._startMatrix[type]=view;},buildStage:function(gameboard){this._tileCount=gameboard.length;this._currentTile=0;this.addSprite(this._currentTile);},addNextSprite:function(gameboard){this._currentTile++;if(this._currentTile<this._tileCount){this.addSprite(this._currentTile);}else if(this._currentTile==this._tileCount){this.init2();}},addRotater:function(x,y,w,h){var data={container:"mask",id:"rotater",className:"rotater",x:x,y:y,w:w,h:h}
this._rotater=new Tile_Controller();var newView=new NonGraphic_View();this._rotater.bindView(newView,data);this._rotater.hide();},addStage:function(x,y,w,h){var data={container:"rotater",id:"stage",className:"stage",x:x,y:y,w:w,h:h}
this._stage=new Stage_Controller();var newView=new NonGraphic_View();this._stage.bindView(newView,data);this._stage.setMainController(this);},addSprite:function(id){this._stageSpriteArray.push(this.createSprite(id));},createSprite:function(id){var gamePiece=this._mainModel.getGameBoard()[id];var classAcronym=gamePiece.type;var startFrame=(gamePiece.startFrame==undefined)?0:gamePiece.startFrame
var data={className:this._mainModel.getGameboardClasses()[classAcronym],imgs:this._mainModel.getGameboardImageLookup()[classAcronym],listener:gamePiece.listener,listenerString:gamePiece.listener,listener1:gamePiece.listener1,listenerString1:gamePiece.listener1,listener2:gamePiece.listener2,listenerString2:gamePiece.listener2,thoughtType:gamePiece.thoughtType,objectType:gamePiece.objectType,visibility:gamePiece.state,stickyHoldingOffset:gamePiece.stickyHoldingOffset,IDOverride:gamePiece.IDOverride,dropTargetFunction:gamePiece.dropTargetFunction,moveObject:gamePiece.moveObject,id:'sprite_tile'+id,stage:"stage",x:gamePiece.x,y:gamePiece.y,w:gamePiece.w,h:gamePiece.h,container:this._stage.getViewID(),startFrame:startFrame}
var newTile=this._stage.addTile(data);if(newTile.getThoughtType!=undefined&&newTile.getThoughtType()!=undefined){this.updateMatrixViewPointer(newTile.getThoughtType(),newTile);}
if(newTile.getClass()!="Tile"&&newTile.getClass()!="Mobile"){var data={controller:newTile,id:id}
this.registerRect(data)}
if(data.IDOverride=="swipeInterface"){this._swipeInterface=newTile;}
return{_name:newTile.getViewID(),_classReference:newTile};},registerPairs:function(){var max=this._mainModel.getGameBoard().length;for(var i=0;i<max;i++){var spriteToCheck=this._stageSpriteArray[i]._classReference;if(spriteToCheck.hasListener()){var listener=spriteToCheck.getListenerString();var re=new RegExp(listener,"gi");for(var j=0;j<this._stageSpriteArray.length;j++){var name=this._stageSpriteArray[j]._name;if(name.match(re)!=null){break;}}
spriteToCheck.setListener(this._stageSpriteArray[j]._classReference);}}},catchKeyDown:function(event){var key=(event.which)
if(String.fromCharCode(key)=="W"){this.finishLastMove();this._player.startWalk();}
if(String.fromCharCode(key)=="X"){this.finishLastMove();this._player.startTurnRight()
this.rotateStage(this._angle-=180,180);}
if(String.fromCharCode(key)=="A"){this.finishLastMove();this._player.startTurnLeft();this.rotateStage(this._angle+=90);}
if(String.fromCharCode(key)=="D"){this.finishLastMove();this._player.startTurnRight()
this.rotateStage(this._angle-=90);}
if(String.fromCharCode(key)=="K"){this.pickUpItem();}
if(String.fromCharCode(key)=="L"){if(!this._player.getIsHoldingObject()){this.interactWithStationaryItem();}else{this.stickyObjectDoSomething();}}},catchKeyUp:function(event){var key=(event.which)
if(key==87){this._player.stopWalk();}
if(key!=87){this._player.stopWalk();}
if(key==75){if(this._player.getIsHoldingObject()){this.movementProgress();}}},catchKeyPress:function(event){var key=(event.which)
if(String.fromCharCode(key)=="w"){this.finishLastMove();this._stage.moveStage(this._moveDistance,this._stageRotation,this._canMoveForward);}},rotateStage:function(degrees,rot){this._canMoveForward=true;var remainder=(degrees/360)%1;if(remainder<0){var percent=1+remainder;}else{var percent=remainder;}
this._lastRotation=this._stageRotation
this._stageRotation=360*percent;this.getPlayerPositionWhileTurning();if(rot!=180){var _duration=200;}else{var _duration=300;}
$('#rotater').animate({target:degrees},{step:function(now,fx){$(this).css('-webkit-transform','rotate('+now+'deg)');$(this).css('-moz-transform','rotate('+now+'deg)');$(this).css('transform','rotate('+now+'deg)');},duration:_duration,easing:'easeOutCirc',complete:this.checkForHitRotate.bind(this)});},resetPosition:function(hitObstacle,type,previousMoves){var target=hitObstacle[0];var type=hitObstacle[1];var targetRect=target._classReference.getRect();var targetRectAdjusted=this.returnStageRectAdjustedForOffset(targetRect);var targetName=target._classReference.getViewDIV();var playerPointOnStage=this._player.transformPlayerToStage($('#stage').position(),this._stageRotation,this._mainModel.getStageWidth(),this._mainModel.getStageHeight());if(type=="head"){var playerRectAdjusted=this._player.getTransformedHeadRect(playerPointOnStage,this._stageRotation);}else if(type=="torso"){var playerRectAdjusted=this._player.getTransformedTorsoRect(playerPointOnStage,this._stageRotation);}
var direction=this._stage.repositionStage(targetRectAdjusted,playerRectAdjusted,this._stageRotation,previousMoves);this.movementProgress();return direction},finishLastMove:function(){$('#rotater').finish();$('#stage').finish();},getPlayerLocation:function(){var playerOnStage=this._player.transformPlayerToStage($('#stage').position(),this._stageRotation,this._mainModel.getStageWidth(),this._mainModel.getStageHeight());var loc={x:playerOnStage.x,y:playerOnStage.y}
return loc;},stickyObjectLifted:function(data){this._activeStickyObject=data.controller;this._player.setIsHoldingObject(true);this.movementProgress();},stickyObjectDropped:function(data){var stickyObject=data.controller;this._activeStickyObject=null;var rectData=this.getPlayerTransformRect();stickyObject.setDroppedRect(rectData,this._stageRotation,this._player);var id=stickyObject.getViewID().replace("sprite_tile","");var hitTarget=this.checkForDropTarget(stickyObject);if(!hitTarget){var data={controller:stickyObject,id:Number(id)}
this.registerRect(data);}},stickyObjectDoSomething:function(){this._activeStickyObject.actedUpon();},checkForDropTarget:function(stickyObject){var results=this.checkForInteraction();if(results.length>0){for(var i=0;i<results.length;i++){var spriteToCheck=results[i].sprite;var hitDropTarget=this.dropTargetActions(spriteToCheck,stickyObject);if(hitDropTarget){this._player.setIsHoldingObject(false);return true;}}}
return false;},pickUpItem:function(target){this._player.stopWalk();if(this._player.getIsHoldingObject()){this._player.startInteract();this.movementProgress();this._player.setIsHoldingObject(false);if(this.getRandomInt(0,4)!=1){this.interactionExtendedActions(this._activeStickyObject,this.getRandomInt(1,4));}
this._activeStickyObject.attachUnattach();return;}
if(this._player.getIsHoldingObject()){return;}
this._player.startInteract();if(target==undefined){var results=this.checkForInteraction();}else{var results=this.checkForInteraction(target);}
if(results.length>0){for(var i=0;i<results.length;i++){var spriteToCheck=results[i].sprite;if(spriteToCheck.getViewDivClass("sticky")){this._player.setIsHoldingObject(true);spriteToCheck.attachUnattach();this.interactionResponse(results[i].sprite);break;}}}},interactWithStationaryItem:function(target){this._player.stopWalk();this._player.startInteract();if(target==undefined){var results=this.checkForInteraction();}else{var results=this.checkForInteraction(target);}
if(results.length>0){for(var i=0;i<results.length;i++){this.interactionResponse(results[i].sprite,results[i].direction);var interactedObject=(target==undefined)?results[i].interactedObject._classReference:target;if(this.getRandomInt(0,4)!=1){var intensity;if(interactedObject.getThoughtType()=="frontDoor"){intensity=1;}else{intensity=this.getRandomInt(1,4);}
if(interactedObject.getThoughtType()!=undefined){this.interactionExtendedActions(interactedObject,intensity);}}}}},checkForInteraction:function(target){if(target==undefined){var predictedObjectArray=this._lastObstacles;}else{var predictedObjectArray=[target];}
var playerOnStage=this._player.transformPlayerToStage($('#stage').position(),this._stageRotation,this._mainModel.getStageWidth(),this._mainModel.getStageHeight());var playerRect=this._player.getTransformedRect(playerOnStage,this._stageRotation,this._quadSize);var possibleInteraction=false;var direction;var results=new Array();for(var i=0;i<predictedObjectArray.length;i++){if(target==undefined){var spriteToCheck=this._stageSpriteArray[predictedObjectArray[i]]._classReference;}else{var spriteToCheck=predictedObjectArray[i];}
var targetRect=spriteToCheck.getRect();var catchableDistance=20;switch(this._stageRotation){case 0:if((targetRect.bottom>=playerRect.top-catchableDistance&&targetRect.bottom<=playerRect.bottom)&&(targetRect.right>=playerRect.left-5&&targetRect.left<=playerRect.right+5)){direction="UP";possibleInteraction=true;}
break;case 90:if((targetRect.right>=playerRect.left-catchableDistance&&targetRect.right<=playerRect.right)&&(targetRect.top<=playerRect.bottom+5&&targetRect.bottom>=playerRect.top-5)){direction="LEFT";possibleInteraction=true;}
break;case 180:if((targetRect.top<=playerRect.bottom+catchableDistance&&targetRect.top>playerRect.bottom)&&(targetRect.right>=playerRect.left-5&&targetRect.left<=playerRect.right+5)){direction="DOWN";possibleInteraction=true;}
break;case 270:if((targetRect.left<=playerRect.right+catchableDistance&&targetRect.left>playerRect.left)&&(targetRect.top<=playerRect.bottom+5&&targetRect.bottom>=playerRect.top-5)){direction="RIGHT";possibleInteraction=true;}
break;}
if(possibleInteraction){if(target==undefined){var isInteractive=$('#'+this._stageSpriteArray[predictedObjectArray[i]]._name).hasClass("interactive");}else{var isInteractive=target.getViewDIV().hasClass("interactive");}
if(isInteractive){if(target==undefined){results.push({sprite:spriteToCheck,interactedObject:this._stageSpriteArray[predictedObjectArray[i]],direction:direction});}else{results.push({sprite:spriteToCheck,interactedObject:target,direction:direction});}}
possibleInteraction=false;}}
return results;},checkForHitRotate:function(){this._player.stopWalk();this.checkForHit();},checkForHit:function(){this.movementProgress();var hitObstacle=this.getHits();if(hitObstacle[0]){var hits=hitObstacle[2];var previousMoves=new Array();for(var i=0;i<hits.length;i++){var isObstacle=hits[i][0]._classReference.getViewDIV().hasClass("obstacle");if(isObstacle){this._canMoveForward=false;previousMoves.push(this.resetPosition(hits[i],hitObstacle[3],previousMoves));clearInterval(this._touchWalkInterval);this._player.stopWalk();}}}else{this._canMoveForward=true;}
this._lastObstacles=hitObstacle[1];},getHits:function(){var mergedQuadrants=this.returnPossibleTargets();var hits=new Array();for(var i=0;i<mergedQuadrants.length;i++){var k='#'+this._stageSpriteArray[mergedQuadrants[i]]._name;var hit=false;if($('#playerHead').objectHitTest({"object":$(k),"transparency":false})&&this._stageSpriteArray[mergedQuadrants[i]]._classReference.getViewVisibility()){var playerSegment='head';hit=true;}
if($('#playerTorso').objectHitTest({"object":$(k),"transparency":false})&&this._stageSpriteArray[mergedQuadrants[i]]._classReference.getViewVisibility()){var playerSegment='torso';hit=true;}
if(hit&&this._stageSpriteArray[mergedQuadrants[i]]._classReference.getViewVisibility()){hits.push([this._stageSpriteArray[mergedQuadrants[i]],playerSegment]);}}
if(hits.length>0){return([true,mergedQuadrants,hits,playerSegment]);}else{return([false,mergedQuadrants]);}},getRotationDegrees:function(obj){var matrix=obj.css("-webkit-transform")||obj.css("-moz-transform")||obj.css("-ms-transform")||obj.css("-o-transform")||obj.css("transform");if(matrix!=='none'){var values=matrix.split('(')[1].split(')')[0].split(',');var a=values[0];var b=values[1];var angle=Math.round(Math.atan2(b,a)*(180/Math.PI));}else{var angle=0;}
return angle;},returnStageRectAdjustedForOffset:function(rect){var newRect={top:0,right:0,bottom:0,left:0};for(var i in rect){newRect[i]=rect[i];}
return(newRect);},returnRoundedRectAndDifferences:function(rect){var t=Math.floor(rect.top/this._quadSize);var r=Math.floor(rect.right/this._quadSize);var b=Math.floor(rect.bottom/this._quadSize);var l=Math.floor(rect.left/this._quadSize);var vDiff=b-t;var hDiff=r-l;var data={t:t,r:r,b:b,l:l,hDiff:hDiff,vDiff:vDiff}
return(data);},setCanMoveForward:function(data){this._canMoveForward=data.bool;},createHitTestQuadrants:function(){var quadsColumns=(this._mainModel.getStageWidth()/this._quadSize)+1;var quadsRows=(this._mainModel.getStageHeight()/this._quadSize)+1;for(var i=0;i<quadsRows;i++){this._hitTestQuadrants[i]=new Array();for(var j=0;j<quadsColumns;j++){this._hitTestQuadrants[i].push(new Array());}}},registerRect:function(data){var id=data.id;var tile=data.controller;var tileToAdd=tile;var rect=tileToAdd.getRect();var data=this.returnRoundedRectAndDifferences(rect);if(tile.getClass()!="Tile"){this._hitTestQuadrants[data.t][data.l].push(id);tileToAdd.registerAQuad([data.t,data.l,id]);if(data.hDiff==1){this._hitTestQuadrants[data.t][data.l+1].push(id);tileToAdd.registerAQuad([data.t,(data.l+1),id]);}
if(data.vDiff==1){this._hitTestQuadrants[data.t+1][data.l].push(id);tileToAdd.registerAQuad([(data.t+1),data.l,id]);}
if(data.hDiff==1&&data.vDiff==1){this._hitTestQuadrants[data.t+1][data.l+1].push(id);tileToAdd.registerAQuad([(data.t+1),(data.l+1),id]);}}},removeRect:function(data){var temp=this._hitTestQuadrants[data.quads[0]][data.quads[1]];for(var i=0;i<temp.length;i++){if(temp[i]==data.quads[2]){this._hitTestQuadrants[data.quads[0]][data.quads[1]].splice(i,1);break;}}},registerPlayer:function(data){var rect={top:data.y,right:(data.x+data.w),bottom:(data.y+data.h),left:data.x}
var data=this.returnRoundedRectAndDifferences(rect);var quadrantsToMerge=new Array();quadrantsToMerge.push(this._hitTestQuadrants[data.t][data.l]);if(data.hDiff==1){quadrantsToMerge.push(this._hitTestQuadrants[data.t][data.l+1]);}
if(data.vDiff==1){quadrantsToMerge.push(this._hitTestQuadrants[data.t+1][data.l]);}
if(data.hDiff==1&&data.vDiff==1){quadrantsToMerge.push(this._hitTestQuadrants[data.t+1][data.l+1]);}
var mergedQuadrants=this.mergeQuadrants(quadrantsToMerge);return(mergedQuadrants);},returnPossibleTargets:function(){var playerOnStage=this._player.transformPlayerToStage($('#stage').position(),this._stageRotation,this._mainModel.getStageWidth(),this._mainModel.getStageHeight());var point=playerOnStage;var possibleTargets=this.registerPlayer(point);return possibleTargets;},mergeQuadrants:function(a){var mergedQuadrants=new Array();var alreadyExists=false;for(var i=0;i<a.length;i++){for(var j=0;j<a[i].length;j++){mergedQuadrants.push(a[i][j]);}}
var cleanedQuadrants=new Array();var arrayLength=mergedQuadrants.length;for(var k=0;k<arrayLength;k++){var last=mergedQuadrants.shift();if(!this.checkForDuplicates(last,mergedQuadrants)){cleanedQuadrants.push(last);}}
return cleanedQuadrants;},checkForDuplicates:function(item,a){for(var i=0;i<a.length;i++){if(a[i]==item){return true;}}
return false;},getPlayerTransformRect:function(){var playerOnStage=this._player.transformPlayerToStage($('#stage').position(),this._stageRotation,this._mainModel.getStageWidth(),this._mainModel.getStageHeight());var playerRect=this._player.getTransformedRect(playerOnStage,this._stageRotation,this._quadSize);return(playerRect);},getPlayerPositionWhileTurning:function(){if(this._player.getIsHoldingObject()){var playerOnStage=this._player.transformPlayerToStage($('#stage').position(),this._lastRotation,this._mainModel.getStageWidth(),this._mainModel.getStageHeight());var playerRect=this._player.getTransformedRect(playerOnStage,this._lastRotation,this._quadSize);this._activeStickyObject.stickForTurn(playerRect);}},transformObjectToStageRotation:function(position,stageRotation,objectWidth,objectHeight){var loc={x:position.left,y:position.top};var objectW=objectWidth;var objectH=objectHeight;switch(stageRotation){case 0:var x=-(loc.x+(objectW/2));var y=-(loc.y+(objectH/2));var w=objectW;var h=objectH;break;case 90:var x=-(loc.y+(objectH/2));var y=(loc.x-(objectW/2));var w=objectH;var h=objectW;break;case 180:var x=loc.x-(objectW/2)
var y=loc.y-(objectH/2)
var w=objectW;var h=objectH;break;case 270:var x=(loc.y-(objectH/2));var y=-(loc.x+(objectW/2));var w=objectH;var h=objectW;break;}
var data={x:Math.round((x)),y:Math.round((y)),w:w,h:h}
return data;},interactionResponse:function(spriteToCheck,direction){if(spriteToCheck.getViewDivClass("door")&&spriteToCheck.getViewVisibility()){spriteToCheck.actedUpon();this.setCanMoveForward({bool:true});}else if(spriteToCheck.getViewDivClass("movable")){spriteToCheck.actedUpon(direction);this.setCanMoveForward({bool:true});}else if(spriteToCheck.hasListener()){if(!spriteToCheck.getViewDivClass("door")&&!spriteToCheck.getViewDivClass("sticky")){spriteToCheck.actedUpon();}}else{if(this.getRandomInt(0,8)!=1){spriteToCheck.actedUpon();}else{console.log('your interaction with the item did not work');}}},interactionExtendedActions:function(interactedObject,intensity){var thoughtType=interactedObject.getThoughtType();var objectType=interactedObject.getObjectType();if(thoughtType==undefined){return;}
this._MIND.addThought(interactedObject.getViewID(),thoughtType,objectType,intensity,this.getPlayerLocation());},dropTargetActions:function(spriteToCheck,droppedClassReference){if(spriteToCheck.getViewDivClass("dropTarget")){spriteToCheck.actedUpon(droppedClassReference);return true;}
return false;},movementProgress:function(){if(this._player.getIsHoldingObject()){this._activeStickyObject.stickToPlayer(this.getPlayerTransformRect(),this._stageRotation,this._player);}},registerHingedDoors:function(){var max=this._mainModel.getGameBoard().length;for(var i=0;i<max;i++){var spriteToCheck=this._stageSpriteArray[i]._classReference;if(spriteToCheck.hasMultipleListeners()){for(var count=1;count<3;count++){var listener=spriteToCheck["getListenerString"+count]();var re=new RegExp(listener,"gi");for(var j=0;j<this._stageSpriteArray.length;j++){var name=this._stageSpriteArray[j]._name;if(name.match(re)!=null){break;}}
spriteToCheck["setListener"+count](this._stageSpriteArray[j]._classReference);}}}},dropTargetHamper:function(data){var droppedItemController=data.droppedItemController;var temp=data.target.getViewLoc();var loc={x:temp.left,y:temp.top}
this._topZIndex++;droppedItemController.setViewLoc(((loc.x+5)+this.getRandomInt(0,25)),((loc.y+3)+this.getRandomInt(0,10)));droppedItemController.getViewDIV().css('z-index',String(this._topZIndex));},dropTargetBookcase:function(data){var droppedItemController=data.droppedItemController;droppedItemController.getViewDIV().hide();for(var i in this._stageSpriteArray){if(this._stageSpriteArray[i]._name=="bookInBookcase"){this._stageSpriteArray[i]._classReference.actedUpon();}}},getRandomInt:function(min,max){return Math.floor(Math.random()*(max-min))+min;},addThoughtBubble:function(){var thoughtInfo=this._mainModel.getThoughtInfo();var classAcronym=thoughtInfo.type;var imageControllerData={className:this._mainModel.getGameboardClasses()[classAcronym],imagePath:this._mainModel.getGameboardImageLookup()[classAcronym],id:'thoughtBubble',container:"body",imgs:this._mainModel.getGameboardImageLookup()[classAcronym],x:thoughtInfo.x,y:thoughtInfo.y,w:thoughtInfo.w,h:thoughtInfo.h}
var stackedAnimationControllerData={id:'stackedAnimations',container:"",x:thoughtInfo.x,y:thoughtInfo.y,w:thoughtInfo.w,h:thoughtInfo.h}
this._thoughtBubble=new ThoughtBubble_Controller();var newView=new ThoughtBubble_View();this._thoughtBubble.bindView(newView,imageControllerData,stackedAnimationControllerData);this.addThoughtAnimations();},addThoughtAnimations:function(){var thoughtAnimations=this._mainModel.getThoughtAnimations();for(var i=0;i<thoughtAnimations.length;i++){var frames=new Array();for(var j=0;j<thoughtAnimations[i].frameCount;j++){frames.push(thoughtAnimations[i].frameRoot+j+thoughtAnimations[i].frameType);}
var data={container:"",name:thoughtAnimations[i].name,id:i,className:thoughtAnimations[i].className,x:thoughtAnimations[i].x,y:thoughtAnimations[i].y,w:thoughtAnimations[i].w,h:thoughtAnimations[i].h,imgs:frames,startFrame:0,classContainer:null}
this._thoughtBubble.addAnimationSequence(data);}},addMask:function(){var maskInfo=this._mainModel.getMaskInfo();var classAcronym=maskInfo.type;var data={className:this._mainModel.getGameboardClasses()[classAcronym],imagePath:this._mainModel.getGameboardImageLookup()[classAcronym],id:'masker',container:"body",imgs:this._mainModel.getGameboardImageLookup()[classAcronym],x:maskInfo.x,y:maskInfo.y,w:maskInfo.w,h:maskInfo.h}
this._mask=new Tile_Controller();var newView=new StageMask_View();this._mask.bindView(newView,data);this._mask.hide();},addOCD_control:function(){this._MIND=new MIND();this._MIND.init(this._player,this._thoughtBubble,this);},addTimer:function(){var data={className:"timer",id:'timer',container:"body",x:162,y:0,w:60,h:30,duration:this._mainModel.getTimeLimit()}
this._timer=new Timer_Controller();var newView=new Timer_View();this._timer.bindView(newView,data);},addAudio:function(){var data={trackName:"myAudio"}
this._audio=new Audio_Controller();var newView=new Audio_View();this._audio.bindView(newView,data);this._audio.setAudioVolume(10);this.addVolumeControl(this._audio);},addVolumeControl:function(audioInstance){var volumeControlInfo=this._mainModel.getVolumeControlInfo();var classAcronym=volumeControlInfo.type;var diffX=(375-volumeControlInfo.w)-5;var diffY=(559-volumeControlInfo.h)-5;var data={className:this._mainModel.getGameboardClasses()[classAcronym],imagePath:this._mainModel.getGameboardImageLookup()[classAcronym],id:'volumeControl',container:"body",imgs:this._mainModel.getGameboardImageLookup()[classAcronym],x:diffX,y:diffY,w:volumeControlInfo.w,h:volumeControlInfo.h,buttonFunction:volumeControlInfo.buttonFunction,buttonTarget:audioInstance,startFrame:0}
this._volumeControl=new ButtonOnOff_Controller();var newView=new Button_View();this._volumeControl.bindView(newView,data);},addEndScreen:function(){var screenInfo=g_gameboardModel.getGoodEndScreenElements();var data={className:"endScreenGood",id:'endScreenGood',container:"body",x:0,y:0,w:375,h:559,}
this._endScreenGood=new Combination_Controller();var newView=new Combination_View();this._endScreenGood.bindView(newView,data);this._endScreenGood.hide();for(var i=0;i<screenInfo.length;i++){var classAcronym=screenInfo[i].type;var dataNested={container:"endScreenGood",id:'endScreenGood_tile'+i,className:this._mainModel.getGameboardClasses()[classAcronym],x:screenInfo[i].x,y:screenInfo[i].y,w:screenInfo[i].w,h:screenInfo[i].h,imgs:this._mainModel.getGameboardImageLookup()[classAcronym],buttonFunction:screenInfo[i].buttonFunction,IDOverride:screenInfo[i].IDOverride};this._endScreenGood.addTile(dataNested);}
this._endScreenGood.getInterfaceElement("goodEndScreenButton").getView().show();var screenInfo=g_gameboardModel.getBadEndScreenElements();var data={className:"endScreenBad",id:'endScreenBad',container:"body",x:0,y:0,w:375,h:559,}
this._endScreenBad=new Combination_Controller();var newView=new Combination_View();this._endScreenBad.bindView(newView,data);this._endScreenBad.hide();for(var i=0;i<screenInfo.length;i++){var classAcronym=screenInfo[i].type;var dataNested={container:"endScreenBad",id:'endScreenBad_tile'+i,className:this._mainModel.getGameboardClasses()[classAcronym],x:screenInfo[i].x,y:screenInfo[i].y,w:screenInfo[i].w,h:screenInfo[i].h,imgs:this._mainModel.getGameboardImageLookup()[classAcronym],buttonFunction:screenInfo[i].buttonFunction,IDOverride:screenInfo[i].IDOverride};this._endScreenBad.addTile(dataNested);}
this._endScreenBad.getInterfaceElement("badEndScreenButton").getView().show();},getTransformedPoint:function(data,touchX,touchY,stageRotation){var centerX=data.x+38;var centerY=data.y+45;switch(this._stageRotation){case 0:var targetX=touchX-this._mainModel.getRotaterX();var targetY=touchY-this._mainModel.getRotaterY();var x=centerX+targetX;var y=centerY+targetY;break;case 90:var targetX=touchX-this._mainModel.getRotaterX();var targetY=touchY-this._mainModel.getRotaterY();var x=centerX+targetY;var y=centerY-targetX;break;case 180:var targetX=touchX-this._mainModel.getRotaterX();var targetY=touchY-this._mainModel.getRotaterY();var x=centerX-targetX;var y=centerY-targetY;break;case 270:var targetX=touchX-this._mainModel.getRotaterX();var targetY=touchY-this._mainModel.getRotaterY();var x=centerX-targetY;var y=centerY+targetX;break;}
var inFront=(targetY<0)?true:false;var data={x:x,y:y,inFront:inFront}
return data;},getPlayer:function(){return(this._player);},getStage:function(){return(this._stage);},getStageRotation:function(){return(this._stageRotation);},getCanMoveForward:function(){return(this._canMoveForward);},getMoveDistance:function(){return(this._moveDistance);},getStageSpriteArray:function(){return(this._stageSpriteArray);},getHitTestQuadrants:function(){return this._hitTestQuadrants;},setTouchWalkInterval:function(intervalRef){this._touchWalkInterval=intervalRef;},updateThoughtBubbleLoc:function(x,y){this._thoughtBubble.setViewLoc(x,y);},updateMask:function(degrees,point){this._mask.setViewRotaion(degrees);this._mask.setViewLoc(point[0],point[1]);},showGameDisplay:function(){this._gameActive=true;this._mask.show();this._rotater.show();this._player.show();g_eventHandler.dispatchAnEvent("startClock",{});g_eventHandler.dispatchAnEvent("startAudio",{});this._volumeControl.getView().show();this.turnOnRandomizedItems();g_eventHandler.dispatchAnEvent("changeZIndex",{});},gameOver:function(){g_eventHandler.dispatchAnEvent("pauseAudio",{});this._gameOver=true;var rectToCheck=this.getPlayerTransformRect();if(rectToCheck.bottom<110&&rectToCheck.left>850&&rectToCheck.right<1020){var decision=this.getRandomInt(0,10);if(decision>=7){this._endScreenGood.makeActive();}else{this._endScreenBad.makeActive();}}else{this._endScreenBad.makeActive();}
this._volumeControl.getView().hide();this._timer.hide();this._swipeInterface.hide();g_eventHandler.dispatchAnEvent("kill",{});},screenRotatedPortrait:function(){if(this._gameActive){this._mask.show();this._rotater.show();this._player.show();if(!this._gameOver){g_eventHandler.dispatchAnEvent("resumeThought",{});g_eventHandler.dispatchAnEvent("resumeAudio",{});g_eventHandler.dispatchAnEvent("resumeClock",{});this._timer.show();this._volumeControl.getView().show();}else{var active=this._endScreenGood.getActive();if(active){this._endScreenGood.show();}else{this._endScreenBad.show();}}}},screenRotatedLandscape:function(){if(this._gameActive){this._mask.hide();this._rotater.hide();this._player.hide();g_eventHandler.dispatchAnEvent("pauseClock",{});g_eventHandler.dispatchAnEvent("pauseAudio",{});if(!this._gameOver){g_eventHandler.dispatchAnEvent("pauseThought",{});}else{var active=this._endScreenGood.getActive();if(active){this._endScreenGood.hide();}else{this._endScreenBad.hide();}}
this._timer.hide();this._volumeControl.getView().hide();}},checkPositionForFinish:function(data){var rectToCheck=this.getPlayerTransformRect();if(data.type=="frontDoor"&&rectToCheck.bottom<150){this.gameOver();}},restartGame:function(){$('#rotater').css('-webkit-transform','rotate('+0+'deg)');$('#rotater').css('-moz-transform','rotate('+0+'deg)');$('#rotater').css('transform','rotate('+0+'deg)');this._stage.setViewLoc(this._mainModel.getStageStartX(),this._mainModel.getStageStartY());g_eventHandler.dispatchAnEvent("resetPosition",{});this._timer.setTotalTime(3);g_eventHandler.dispatchAnEvent("startClock",{});g_eventHandler.dispatchAnEvent("restartAudio",{});this._timer.show();this._volumeControl.getView().show();g_eventHandler.dispatchAnEvent("resetState",{});this.populatePretriggeredControls(this._potentialThoughtArray);this._endScreenGood.hide();this._endScreenBad.hide();this.turnOnRandomizedItems();this._swipeInterface.show();console.log('game restarted');}});