this._relatedMatrix = {
		candle:["lampBR", "lampOffice", "lampLR"],
		lampBR:["lampOffice", "lampLR", "candle"],
		lampOffice:["lampLR", "candle", "lampBR"],
		bookOffice:[],
		chairBar:[],
		chairTable:[],
		matCorner:["sock", "pant", "shirt", "underwear"],
		kitchenSink:["bathtub", "bathSink"],
		kitchenRange:[],
		frontDoor:[],
		tv:[],
		lampLR:["lampLR", "lampOffice", "lampBR"],
		toilet:[],
		bathtub:["bathSink", "kitchenSink"],
		bathSink:["bathtub", "kitchenSink"],
		sock:["matCorner", "pant", "shirt", "underwear"],
		underwear:["matCorner", "pant", "shirt", "sock"],
		shirt:["matCorner", "pant", "underwear", "sock"],
		pant:["matCorner", "shirt", "underwear", "sock"]
	};